services:
  database:
    platform: linux/x86_64
    image: mysql:8.0.39
    restart: always
    container_name: db_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - TZ=Asia/Seoul

    command:
      - '--lower_case_table_names=1'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_general_ci'

    volumes:
      - ./data:/var/lib/mysql

    networks:
      - springboot-mysql-net

  springboot-app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: springboot
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/mydb?useUnicode=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATAOSOURCE_PASSWORD: 1234
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    external: true
