spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db_mysql:3306/mydb?useUnicode=true&serverTimezone=Asia/Seoul
    username: user
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # 콘솔 로그에서 데이터베이스에서 실행된 쿼리문을 볼 수 있다
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000
